name: Bug Report
description: TESTING, DON'T USE! If something isn't working as expected.
title: "[Bug]: "
labels: ["bug", "triage"]

body:
- type: checkboxes
attributes:
label: Is there an existing issue for this?
description: Please search to see if an issue already exists for the bug you encountered.
options:
- label: I have searched the existing issues
required: true
- type: checkboxes
id: hardware
attributes:
label: Used Hardware?
description: Please let us know what hardware you are using.
options:
- label: Wemos D1 Mini
- label: ESP-01 (512KB Flash)
- label: ESP-01S (1MB Flash)
- label: Other (please write your hardware in 'What happened?')
required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
 - type: textarea
  attributes:
    label: Steps To Reproduce
    description: If applicable, steps to reproduce the behavior.
    placeholder: |
      1. Go to...
      2. Click on...
      3. See error...
  validations:
    required: false
 - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2.x.x (Default)
        - 1.x.x (Depreciated)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  validations:
    required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant livejson output
      description: Please copy and paste your livejson-output (http://IP_of_your_ESP/livejson). This will be automatically formatted into code, so no need for backticks.
      render: json
   validations:
    required: true
