name: 🚀 Feature Request
description: I have a suggestion (and may want to implement it 🙂)!
title: "[HELP] <title>"
body:
- type: textarea
  attributes:
    label: Describe your problem
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
